test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,7 +34,8 @@ commands:
             if (( $SUCCESS == 1 ));
             then
               cd ~/project/backend
-              exit 0
+              pwd
+              ls
               npm install
               npm run migrations:revert
             fi
@@ -284,7 +285,7 @@ jobs:
             echo $URL
             if curl -s $URL | grep "ok"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi
@@ -295,11 +296,11 @@ jobs:
             echo $URL 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi      
-      - destroy_environment
+      # - destroy_environment
       - revert-migrations      
 
   cloudfront-update:
@@ -319,13 +320,13 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/OLD_WORKFLOW_ID
-      # - run:
-      #     name: Update cloudfront distribution
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/cloudfront.yml \
-      #         --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-      #         --stack-name InitialStack 
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --stack-name InitialStack 
       - destroy_environment
       - revert-migrations                   
 
@@ -366,22 +367,22 @@ workflows:
       #     requires: [build-backend]
       # - scan-frontend:
       #     requires: [build-frontend]
-      - deploy-infrastructure #:
+      # - deploy-infrastructure :
       #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       #     filters:
       #       branches: 
       #         only: [master]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend :
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [deploy-backend]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend :
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      - smoke-test #:
+          # requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [deploy-backend]
+      # - cleanup:
+      #     requires: [cloudfront-update]
